### ISSUE TITLE
Release 2.0.4 supporting stable rust

### ISSUE THREAD

**Issue by rillian** [Razican/vsop87-rs#26]
BTW, if you're planning to release the develop branch as 2.1.0, would you consider also making a 2.0.4 release? It looks like the simd code requires nightly, and it would be nice to have a version which works with stable rust.

**Comment by Razican** [comment]
In principle, SIMD doesn't require nightly at all. It's available since Rust 1.27 on stable :) so there should be no issue when upgrading. Also, it will be behind a feature flag if it's something you want to avoid (it adds a bit of checked unsafe code).

**Comment by rillian** [comment]
Ok, I wondered about that. In any case, with the changes you've made to the release/2.1.0 it now builds for me on stable.
